### ISSUE TITLE
App Crashing on launch

### ISSUE THREAD

**Issue by CosmicEternityCD** [victorlobe/iOS-6-Simulator-written-in-Swift#2]
I installed this ipa onto my iPhone 11 Pro using Sideloadly (iOS 15.7), and it crashes within 1 second of opening the app, could you fix this please?

**Comment by victorlobe** [comment]
Hello, thanks for your comment. I have fixed the bug in the newest version :)

**Comment by CosmicEternityCD** [comment]
It doesnt seem to be fixed

**Comment by Soteris24** [comment]
> It doesnt seem to be fixed

yes same with me

**Comment by victorlobe** [comment]
Hello, I just made a commit that should fix the App on newer Versions.
