### ISSUE TITLE
Crashes on launch (iPadOS 16.6, 5th gen)

### ISSUE THREAD

**Issue by SatinFoil** [victorlobe/iOS-6-Simulator-written-in-Swift#4]
iPad 5th gen
iPadOS 16.6
Installed with Trollstore

Whenever it launches, it crashes. I see it in the top left for a second before that. I think iPadOS has iOS support, but I don't think it's enabled or whatever, since I see it in the top left before crashing. I think that might be the problem. Could you enable that?

Fyi, I don't know anything about coding iOS apps.

**Comment by victorlobe** [comment]
Hello, I just made a commit that should fix the App on newer Versions.
